"""HTML reporter — generates a self-contained diagnostic report."""

from __future__ import annotations

from typing import Any

from analyzers.routing import RoutingReport
from analyzers.context import ContextReport
from analyzers.prompt_order import PromptOrderReport
from analyzers.prompt_compression import CompressionReport
from analyzers.thinking import ThinkingReport
from reporters.json_report import (
    routing_to_dict,
    context_to_dict,
    prompt_order_to_dict,
    compression_to_dict,
    thinking_to_dict,
)
from utils.tokens import format_tokens


def pct(v: float) -> str:
    return f"{v * 100:.1f}%"


def health_badge(health: str) -> str:
    colors = {"green": "#22c55e", "yellow": "#eab308", "red": "#ef4444"}
    return f'<span class="badge" style="background:{colors.get(health, "#888")}"></span>'


def severity_badge(sev: str) -> str:
    colors = {"none": "#22c55e", "low": "#eab308", "medium": "#f97316", "high": "#ef4444"}
    return f'<span class="badge" style="background:{colors.get(sev, "#888")}"></span>'


# ── Template ──────────────────────────────────────────────────────────────

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>claw_llm_doctor — Diagnostic Report</title>
<style>
  :root { --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #e6edf3;
          --muted: #8b949e; --accent: #58a6ff; --green: #3fb950; --yellow: #d29922;
          --red: #f85149; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
         background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.5; }
  h1 { color: var(--accent); margin-bottom: 1.5rem; font-size: 1.5rem; }
  h2 { color: var(--accent); margin: 2rem 0 1rem; font-size: 1.2rem;
       border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
  h3 { color: var(--muted); margin: 1rem 0 0.5rem; font-size: 1rem; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
          padding: 1.2rem; margin-bottom: 1rem; }
  .metric { display: inline-block; margin-right: 2rem; margin-bottom: 0.5rem; }
  .metric .label { color: var(--muted); font-size: 0.85rem; }
  .metric .value { font-size: 1.4rem; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; font-size: 0.9rem; }
  th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid var(--border);
       color: var(--muted); font-weight: 600; }
  td { padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border); }
  tr:hover td { background: rgba(88,166,255,0.05); }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .badge { display: inline-block; width: 10px; height: 10px; border-radius: 50%; }
  .bar-container { width: 100%; background: var(--border); border-radius: 4px; height: 8px; }
  .bar-fill { height: 8px; border-radius: 4px; transition: width 0.3s; }
  .tag { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px;
         font-size: 0.8rem; margin-right: 0.3rem; background: var(--border); }
  .tag-red { background: rgba(248,81,73,0.2); color: var(--red); }
  .tag-yellow { background: rgba(210,153,34,0.2); color: var(--yellow); }
  .tag-green { background: rgba(63,185,80,0.2); color: var(--green); }
  .leak-example { background: rgba(248,81,73,0.08); border-left: 3px solid var(--red);
                  padding: 0.5rem 0.75rem; margin: 0.3rem 0; font-size: 0.85rem;
                  border-radius: 0 4px 4px 0; }
  .leak-example code { color: var(--red); font-weight: 600; }
  .sim-bar { display: flex; align-items: center; gap: 0.5rem; margin: 0.15rem 0; font-size: 0.85rem; }
  .sim-bar .idx { color: var(--muted); width: 3rem; text-align: right; }
  footer { margin-top: 3rem; color: var(--muted); font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<h1>claw_llm_doctor &mdash; Diagnostic Report</h1>
{content}
<footer>Generated by claw_llm_doctor v0.1.0</footer>
</body>
</html>
"""


# ── Section renderers ─────────────────────────────────────────────────────


def render_routing(report: RoutingReport) -> str:
    d = routing_to_dict(report)
    s = d["summary"]
    html = '<h2>Layer 1: LM Routing Analysis</h2><div class="card">'

    # Summary metrics
    metrics = [
        ("Total Calls", s["total_calls"]),
        ("Primary", s["primary_calls"]),
        ("Fallback", s["fallback_calls"]),
        ("Primary OK", pct(s["primary_success_rate"])),
        ("Fallback OK", pct(s["fallback_success_rate"])),
        ("Overall OK", pct(s["overall_success_rate"])),
        ("Fallback Rate", pct(s["fallback_trigger_rate"])),
    ]
    for label, val in metrics:
        html += f'<div class="metric"><div class="label">{label}</div><div class="value">{val}</div></div>'
    html += "</div>"

    # Model table
    if d["by_model"]:
        html += "<h3>By Model</h3><table><tr><th>Model</th><th class='num'>Total</th>"
        html += "<th class='num'>Success</th><th class='num'>Failure</th></tr>"
        for model, info in d["by_model"].items():
            html += f"<tr><td>{model}</td><td class='num'>{info['total']}</td>"
            html += f"<td class='num'>{info['success']}</td><td class='num'>{info['failure']}</td></tr>"
        html += "</table>"

    # Error table
    if d["errors"]:
        html += "<h3>Errors</h3><table><tr><th>Code</th><th class='num'>Count</th>"
        html += "<th>Models</th><th>Example</th></tr>"
        for code, info in sorted(d["errors"].items(), key=lambda x: -x[1]["count"]):
            example = info["examples"][0] if info["examples"] else ""
            html += f"<tr><td><span class='tag tag-red'>{code}</span></td>"
            html += f"<td class='num'>{info['count']}</td>"
            html += f"<td>{', '.join(info['models'])}</td><td>{_esc(example)}</td></tr>"
        html += "</table>"

    # Session table
    if d["sessions"]:
        html += "<h3>Sessions</h3><table><tr><th>Session</th><th class='num'>Calls</th>"
        html += "<th class='num'>OK</th><th class='num'>Fail</th><th class='num'>Fallback</th></tr>"
        for sess in d["sessions"]:
            html += f"<tr><td>{_esc(sess['session_key'][:30])}</td>"
            html += f"<td class='num'>{sess['total_calls']}</td>"
            html += f"<td class='num'>{sess['success']}</td>"
            html += f"<td class='num'>{sess['failure']}</td>"
            html += f"<td class='num'>{sess['fallback_triggered']}</td></tr>"
        html += "</table>"

    if report.timeline:
        html += "<h3>Routing Timeline</h3><table><tr><th>Time</th><th>Session</th>"
        html += "<th>Model</th><th>Provider</th><th>Role</th><th>OK</th><th>Duration</th></tr>"
        for e in report.timeline:
            role = "Primary" if e["is_primary"] is True else ("Fallback" if e["is_primary"] is False else "?")
            role_cls = "tag-green" if e["is_primary"] is True else ("tag-yellow" if e["is_primary"] is False else "")
            ok = '<span class="tag tag-green">OK</span>' if e["success"] else '<span class="tag tag-red">FAIL</span>'
            dur = f'{e["duration_ms"]}ms' if e["duration_ms"] is not None else "-"
            html += f"<tr><td>{e['timestamp']}</td><td>{_esc(str(e['session_key'])[:20])}</td>"
            html += f"<td>{_esc(e['model'])}</td><td>{_esc(e['provider'])}</td>"
            html += f'<td><span class="tag {role_cls}">{role}</span></td>'
            html += f"<td>{ok}</td><td class='num'>{dur}</td></tr>"
        html += "</table>"

    if report.fallback_chains:
        html += f"<h3>Fallback Chains ({len(report.fallback_chains)})</h3>"
        for i, chain in enumerate(report.fallback_chains, 1):
            resolved = '<span class="tag tag-green">resolved</span>' if chain["final_success"] else '<span class="tag tag-red">unresolved</span>'
            models = " → ".join(chain["models_tried"])
            html += f'<div class="card"><strong>Chain {i}:</strong> {_esc(models)} {resolved}'
            html += "<table><tr><th class='num'>Step</th><th>Model</th><th>OK</th><th>Error</th><th class='num'>Duration</th></tr>"
            for step, call in enumerate(chain["calls"], 1):
                ok = '<span class="tag tag-green">OK</span>' if call["success"] else '<span class="tag tag-red">FAIL</span>'
                dur = f'{call["duration_ms"]}ms' if call["duration_ms"] is not None else "-"
                err = _esc((call.get("error") or "")[:60])
                html += f"<tr><td class='num'>{step}</td><td>{_esc(call['model'])}</td><td>{ok}</td><td>{err}</td><td class='num'>{dur}</td></tr>"
            html += "</table></div>"

    return html


def render_context(report: ContextReport) -> str:
    html = f'<h2>Layer 3a: Context — {_esc(report.session_key)}</h2><div class="card">'
    metrics = [
        ("Turns", len(report.turns)),
        ("Peak Util", pct(report.peak_utilization)),
        ("Avg Util", pct(report.avg_utilization)),
        ("Compactions", len(report.compaction_events)),
    ]
    for label, val in metrics:
        html += f'<div class="metric"><div class="label">{label}</div><div class="value">{val}</div></div>'
    html += "</div>"

    if report.turns:
        html += "<table><tr><th class='num'>Turn</th><th class='num'>System</th>"
        html += "<th class='num'>Tools</th><th class='num'>History</th>"
        html += "<th class='num'>ToolRes</th><th class='num'>Think</th>"
        html += "<th class='num'>Total</th><th class='num'>Util</th><th>HP</th></tr>"
        for t in report.turns:
            html += f"<tr><td class='num'>{t.turn_index}</td>"
            html += f"<td class='num'>{format_tokens(t.system_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.tool_def_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.history_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.tool_result_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.thinking_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.total_tokens)}</td>"
            html += f"<td class='num'>{pct(t.utilization)}</td>"
            html += f"<td>{health_badge(t.health)}</td></tr>"
        html += "</table>"

    curve = report.growth_curve()
    if curve:
        max_tok = max((pt["total_tokens"] for pt in curve), default=1) or 1
        html += "<h3>Context Growth</h3>"
        for pt in curve:
            w = int((pt["total_tokens"] / max_tok) * 100)
            delta = pt["delta"]
            delta_color = "var(--green)" if delta >= 0 else "var(--red)"
            delta_str = f"+{delta}" if delta >= 0 else str(delta)
            html += f'<div class="sim-bar"><span class="idx">T{pt["turn_index"]}</span>'
            html += f'<div class="bar-container"><div class="bar-fill" style="width:{w}%;background:var(--accent)"></div></div>'
            html += f'<span>{format_tokens(pt["total_tokens"])}</span>'
            html += f'<span style="color:{delta_color}">{delta_str}</span></div>'

    return html


def render_prompt_order(report: PromptOrderReport) -> str:
    stable_tag = '<span class="tag tag-green">STABLE</span>' if report.is_stable else '<span class="tag tag-red">UNSTABLE</span>'
    html = f'<h2>Layer 3b: Prompt Order — {_esc(report.session_key)}</h2><div class="card">'
    html += f'<div class="metric"><div class="label">Turns</div><div class="value">{len(report.turns)}</div></div>'
    html += f'<div class="metric"><div class="label">Ordering</div><div class="value">{stable_tag}</div></div>'
    html += "</div>"

    if report.turns:
        html += f"<h3>Baseline: {_esc(report.turns[0].order_signature)}</h3>"

    if report.order_changes:
        html += "<h3>Order Changes</h3><table><tr><th class='num'>Turn</th><th>Before</th><th>After</th></tr>"
        for ch in report.order_changes:
            html += f"<tr><td class='num'>{ch['turn']}</td><td>{_esc(ch['prev_order'])}</td><td>{_esc(ch['curr_order'])}</td></tr>"
        html += "</table>"

    if report.missing_sections:
        html += "<h3>Missing Sections</h3><table><tr><th class='num'>Turn</th><th>Lost</th></tr>"
        for ms in report.missing_sections:
            tags = "".join(f'<span class="tag tag-red">{_esc(s)}</span>' for s in ms["missing"])
            html += f"<tr><td class='num'>{ms['turn']}</td><td>{tags}</td></tr>"
        html += "</table>"

    return html


def render_compression(report: CompressionReport) -> str:
    html = f'<h2>Layer 3c: Compression — {_esc(report.session_key)}</h2><div class="card">'
    metrics = [
        ("Baseline", f"{report.baseline_length:,} chars"),
        ("Sections", ", ".join(report.baseline_sections)),
        ("Max Loss", pct(report.max_loss_ratio)),
        ("Turns w/ Loss", report.turns_with_loss),
    ]
    for label, val in metrics:
        html += f'<div class="metric"><div class="label">{label}</div><div class="value">{val}</div></div>'
    html += "</div>"

    # Similarity curve
    if report.similarity_curve and len(report.similarity_curve) > 1:
        html += "<h3>Similarity vs Baseline</h3>"
        for i, sim in enumerate(report.similarity_curve):
            w = int(sim * 100)
            color = "#3fb950" if sim > 0.9 else "#d29922" if sim > 0.7 else "#f85149"
            html += f'<div class="sim-bar"><span class="idx">T{i}</span>'
            html += f'<div class="bar-container"><div class="bar-fill" style="width:{w}%;background:{color}"></div></div>'
            html += f"<span>{pct(sim)}</span></div>"

    if report.compactions:
        html += "<h3>Compaction Events</h3><table><tr><th class='num'>Turn</th>"
        html += "<th class='num'>Before</th><th class='num'>After</th>"
        html += "<th class='num'>Ratio</th><th>Lost Sections</th></tr>"
        for c in report.compactions:
            lost = "".join(f'<span class="tag tag-red">{_esc(s)}</span>' for s in c.lost_sections) or "-"
            html += f"<tr><td class='num'>{c.turn_index}</td>"
            html += f"<td class='num'>{c.before_length:,}</td>"
            html += f"<td class='num'>{c.after_length:,}</td>"
            html += f"<td class='num'>{pct(c.compression_ratio)}</td>"
            html += f"<td>{lost}</td></tr>"
        html += "</table>"

    return html


def render_thinking(report: ThinkingReport) -> str:
    html = f'<h2>Layer 3d: Thinking — {_esc(report.session_key)}</h2><div class="card">'
    metrics = [
        ("Thinking Turns", f"{report.turns_with_thinking}/{len(report.turns)}"),
        ("Thinking Ratio", pct(report.overall_thinking_ratio)),
        ("Think Tokens", format_tokens(report.total_thinking_tokens)),
        ("Content Tokens", format_tokens(report.total_content_tokens)),
        ("Leakage Turns", report.turns_with_leakage),
        ("Leakage Rate", pct(report.leakage_rate)),
    ]
    for label, val in metrics:
        html += f'<div class="metric"><div class="label">{label}</div><div class="value">{val}</div></div>'
    html += "</div>"

    # Leakage details
    if report.turns_with_leakage > 0:
        html += "<h3>Leakage Patterns</h3><table><tr><th>Pattern</th><th class='num'>Count</th></tr>"
        for name, count in sorted(report.leakage_pattern_counts.items(), key=lambda x: -x[1]):
            html += f"<tr><td><span class='tag tag-red'>{_esc(name)}</span></td><td class='num'>{count}</td></tr>"
        html += "</table>"

        html += "<h3>Leakage Examples</h3>"
        for turn in report.turns:
            if turn.has_leakage:
                for li in turn.leakage_instances[:3]:
                    html += f'<div class="leak-example">Turn {turn.turn_index} '
                    html += f'[{_esc(li.pattern_name)}]: <code>{_esc(li.matched_text)}</code><br>'
                    html += f'{_esc(li.context)}</div>'

    # Per-turn table
    thinking_turns = [t for t in report.turns if t.has_thinking]
    if thinking_turns:
        html += "<h3>Thinking per Turn</h3><table><tr><th class='num'>Turn</th>"
        html += "<th class='num'>Think</th><th class='num'>Content</th>"
        html += "<th class='num'>Ratio</th><th>Categories</th><th>Leak</th></tr>"
        for t in thinking_turns:
            cats = ", ".join(sorted({b.category for b in t.thinking_blocks}))
            html += f"<tr><td class='num'>{t.turn_index}</td>"
            html += f"<td class='num'>{format_tokens(t.thinking_tokens)}</td>"
            html += f"<td class='num'>{format_tokens(t.content_tokens)}</td>"
            html += f"<td class='num'>{pct(t.thinking_ratio)}</td>"
            html += f"<td>{_esc(cats)}</td>"
            html += f"<td>{severity_badge(t.leakage_severity)}</td></tr>"
        html += "</table>"

    return html


# ── Public API ────────────────────────────────────────────────────────────


def generate_html(
    routing: RoutingReport | None = None,
    contexts: list[ContextReport] | None = None,
    prompt_orders: list[PromptOrderReport] | None = None,
    compressions: list[CompressionReport] | None = None,
    thinkings: list[ThinkingReport] | None = None,
) -> str:
    sections: list[str] = []

    if routing:
        sections.append(render_routing(routing))
    if contexts:
        for c in contexts:
            sections.append(render_context(c))
    if prompt_orders:
        for p in prompt_orders:
            sections.append(render_prompt_order(p))
    if compressions:
        for c in compressions:
            sections.append(render_compression(c))
    if thinkings:
        for t in thinkings:
            sections.append(render_thinking(t))

    return HTML_TEMPLATE.replace("{content}", "\n".join(sections))


def write_html(html: str, output: str) -> None:
    with open(output, "w") as f:
        f.write(html)


def _esc(s: Any) -> str:
    """Escape HTML special characters."""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
